### ISSUE TITLE
There should be a space between the heading and the sorting filter.

### ISSUE THREAD

**Issue by dubey748** [dubey748/Live#33]
![image](https://github.com/dubey748/Live/assets/65311526/6c99d495-ebfe-4637-b1d1-95fdbaf7b198)

**Comment by Kethankrk** [comment]
On it

**Comment by dubey748** [comment]
Please consider using yarn run dev instead of npm run dev to launch the project.

**Comment by Kethankrk** [comment]
I've attempted various approaches, but still the same error. What version of Node.js are you currently using?

**Comment by Kethankrk** [comment]
Anyway, I added the tailwind class for flex gap and sent a PR.

**Comment by dubey748** [comment]
Currently I am using v18.14.2

**Comment by dubey748** [comment]
> Anyway, I added the tailwind class for flex gap and sent a PR.

Thank you so much

**Comment by dubey748** [comment]
I am reopening this issue because I am encountering the same problem with the development, and it has not been resolved yet.
![image](https://github.com/dubey748/Live/assets/65311526/051ffe5e-fb7d-4c95-8cda-e7acb85d5359)

**Comment by dubey748** [comment]
No Problem
